# Generated by Django 5.1.4 on 2025-01-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusicstore', '0004_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disco',
            name='precio_original',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discodestacado',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discodestacado',
            name='precio_original',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Oferta',
        ),
    ]
