# Generated by Django 5.1.4 on 2025-01-17 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymusicstore', '0005_disco_descuento_disco_precio_original_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disco',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='disco',
            name='precio_original',
        ),
        migrations.RemoveField(
            model_name='discodestacado',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='discodestacado',
            name='precio_original',
        ),
    ]
