# Generated by Django 5.1.4 on 2025-01-17 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusicstore', '0006_remove_disco_descuento_remove_disco_precio_original_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.IntegerField(choices=[(20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%')])),
                ('disco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mymusicstore.disco')),
            ],
        ),
    ]
