# Generated by Django 5.1.4 on 2025-01-23 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymusicstore', '0009_registrarusuario_avatar_registrarusuario_biografia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrarusuario',
            name='link',
        ),
    ]
