# Generated by Django 5.1.4 on 2025-01-23 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymusicstore', '0010_remove_registrarusuario_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListaDeseados',
        ),
    ]
