# Generated by Django 5.1.4 on 2025-01-23 05:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusicstore', '0011_delete_listadeseados'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='discos/'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
