# Generated by Django 5.1.4 on 2025-01-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusicstore', '0012_disco_imagen_alter_disco_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
