# Generated by Django 5.1.4 on 2025-01-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusicstore', '0013_alter_disco_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='discodestacado',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discodestacado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='discos/'),
        ),
    ]
