# Generated by Django 5.1.4 on 2025-01-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusicstore', '0014_discodestacado_descripcion_discodestacado_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discodestacado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='discosdestacados/'),
        ),
    ]
