# Generated by Django 5.1.4 on 2025-01-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusicstore', '0015_alter_discodestacado_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('linkedin', models.URLField()),
                ('behance', models.URLField()),
                ('instagram', models.URLField()),
                ('discord', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='contacto/')),
            ],
        ),
    ]
